/**
 * Seed script: Copies generated category images to uploads/homes/ 
 * and inserts/updates categoryGrid in the HomeCMS MongoDB document.
 * 
 * Run from backend folder: node seed_category_grid.js
 */
require('dotenv').config();
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');

// Import the HomeCMS model
const HomeCMS = require('./src/models/HomeCMS');

const CONFIG_KEY = 'home_cms_config';

// Source images (generated by AI)
const SOURCE_IMAGES = [
  {
    src: path.join(__dirname, '..', 'front-end', 'src', 'assets', 'seeds', 'gift_boxes_category.png'),
    filename: 'category-grid-gift-boxes.png',
    title: 'Gift Boxes',
    description: 'Curated collections of premium essentials for discerning tastes.',
    buttonText: 'View Collection',
    targetUrl: '/category/gift-boxes'
  },
  {
    src: path.join(__dirname, '..', 'front-end', 'src', 'assets', 'seeds', 'photo_frames_category.png'),
    filename: 'category-grid-photo-frames.png',
    title: 'Photo Frames',
    description: 'Handcrafted borders designed to turn fleeting moments into permanent art.',
    buttonText: 'View Collection',
    targetUrl: '/category/photo-frames'
  },
  {
    src: path.join(__dirname, '..', 'front-end', 'src', 'assets', 'seeds', 'personalized_gifts_category.png'),
    filename: 'category-grid-personalized-gifts.png',
    title: 'Personalized Gifts',
    description: 'Custom-engraved and tailored keepsakes carrying individual narratives.',
    buttonText: 'View Collection',
    targetUrl: '/category/personalized-gifts'
  }
];

async function seedCategoryGrid() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Ensure uploads/homes directory exists
    const uploadsDir = path.join(__dirname, 'uploads', 'homes');
    if (!fs.existsSync(uploadsDir)) {
      fs.mkdirSync(uploadsDir, { recursive: true });
      console.log('📁 Created uploads/homes directory');
    }

    // Copy images and build categoryGrid array
    const categoryGrid = [];

    for (const item of SOURCE_IMAGES) {
      const destPath = path.join(uploadsDir, item.filename);

      // Check if source image exists
      if (!fs.existsSync(item.src)) {
        console.error(`❌ Source image not found: ${item.src}`);
        console.log(`   Skipping "${item.title}" — place the image at the path above and re-run.`);
        continue;
      }

      // Copy image to uploads/homes/
      fs.copyFileSync(item.src, destPath);
      console.log(`📷 Copied: ${item.filename}`);

      categoryGrid.push({
        title: item.title,
        description: item.description,
        buttonText: item.buttonText,
        targetUrl: item.targetUrl,
        image: `uploads/homes/${item.filename}`
      });
    }

    if (categoryGrid.length === 0) {
      console.error('❌ No images were found to seed. Aborting.');
      process.exit(1);
    }

    // Update or create HomeCMS document
    let config = await HomeCMS.findOne({ key: CONFIG_KEY });
    if (!config) {
      config = new HomeCMS({ key: CONFIG_KEY });
      console.log('📝 Creating new HomeCMS document');
    } else {
      console.log('📝 Updating existing HomeCMS document');
    }

    config.categoryGrid = categoryGrid;
    await config.save();

    console.log(`\n✅ Successfully seeded ${categoryGrid.length} category grid cards!`);
    console.log('\nInserted cards:');
    categoryGrid.forEach((card, i) => {
      console.log(`  ${i + 1}. ${card.title} → ${card.image}`);
    });

  } catch (err) {
    console.error('❌ Seed error:', err.message);
  } finally {
    await mongoose.disconnect();
    console.log('\n🔌 Disconnected from MongoDB');
    process.exit(0);
  }
}

seedCategoryGrid();
